/**
 * Expo Router Navigation Types
 * 
 * Typed route parameters for Expo Router v4.
 * These types are automatically generated by Expo Router when typedRoutes is enabled.
 * 
 * Usage:
 *   import { router } from 'expo-router';
 *   router.push('/chat/[matchId]', { matchId: '123' });
 */

export type RootStackParamList = {
  '(auth)': undefined;
  '(tabs)': undefined;
  '(auth)/login': undefined;
  '(auth)/signup': undefined;
  '(auth)/onboarding': undefined;
  '(auth)/onboarding/index': undefined;
  '(auth)/onboarding/basic-info': undefined;
  '(auth)/onboarding/photos': undefined;
  '(auth)/onboarding/fitness': undefined;
  '(auth)/onboarding/gym-preferences': undefined;
  '(auth)/onboarding/approach-prompt': undefined;
  '(auth)/onboarding/preferences': undefined;
  '(tabs)/discover': undefined;
  '(tabs)/matches': undefined;
  '(tabs)/profile': undefined;
  '(tabs)/chat': undefined;
  '(tabs)/chat/index': undefined;
  '(tabs)/chat/[matchId]': { matchId: string };
  '(tabs)/chat/request/[senderId]': { senderId: string };
};
